apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: urbanconnect
  labels:
    app: temporal
spec:
  selector:
    app: temporal
  ports:
    - port: 7233
      targetPort: 7233
      name: grpc
