apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: urbanconnect
  labels:
    app: minio-init
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: minio-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-init
          image: minio/mc:latest
          command:
            - sh
            - -c
            - |
              mc alias set urbanminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mb urbanminio/$MINIO_BUCKET_NAME --ignore-existing
              mc anonymous set public urbanminio/$MINIO_BUCKET_NAME
              echo "Bucket créé et défini en accès public"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: urbanconnect-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: urbanconnect-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: urbanconnect-secrets
                  key: MINIO_BUCKET_NAME
